# Generated by Django 2.2.6 on 2020-04-19 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0004_send_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucess_Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('signup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wedding.Signup')),
            ],
        ),
    ]
